# Generated by Django 4.0.4 on 2022-05-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_document_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File_save',
            new_name='Document2',
        ),
    ]
