# Generated by Django 4.0.4 on 2022-05-17 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_document_uploadedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uploadedFile',
            new_name='upload',
        ),
    ]
